-- https://github.com/NcknmeX / Eiiy#0666

[Name] = EXP_TAG_GRENADE	                    [Type] = 0
[Name] = EXP_TAG_GRENADELAUNCHER	            [Type] = 1
[Name] = EXP_TAG_STICKYBOMB	                    [Type] = 2
[Name] = EXP_TAG_MOLOTOV	                    [Type] = 3
[Name] = EXP_TAG_ROCKET	                        [Type] = 4
[Name] = EXP_TAG_TANKSHELL	                    [Type] = 5
[Name] = EXP_TAG_HI_OCTANE	                    [Type] = 6
[Name] = EXP_TAG_CAR	                        [Type] = 7
[Name] = EXP_TAG_PLANE	                        [Type] = 8
[Name] = EXP_TAG_PETROL_PUMP	                [Type] = 9
[Name] = EXP_TAG_BIKE	                        [Type] = 10
[Name] = EXP_TAG_DIR_STEAM	                    [Type] = 11
[Name] = EXP_TAG_DIR_FLAME	                    [Type] = 12
[Name] = EXP_TAG_DIR_WATER_HYDRANT	            [Type] = 13
[Name] = EXP_TAG_DIR_GAS_CANISTER	            [Type] = 14
[Name] = EXP_TAG_BOAT	                        [Type] = 15
[Name] = EXP_TAG_SHIP_DESTROY	                [Type] = 16
[Name] = EXP_TAG_TRUCK	                        [Type] = 17
[Name] = EXP_TAG_BULLET	                        [Type] = 18
[Name] = EXP_TAG_SMOKEGRENADELAUNCHER	        [Type] = 19
[Name] = EXP_TAG_SMOKEGRENADE	                [Type] = 20
[Name] = EXP_TAG_BZGAS	                        [Type] = 21
[Name] = EXP_TAG_FLARE	                        [Type] = 22
[Name] = EXP_TAG_GAS_CANISTER	                [Type] = 23
[Name] = EXP_TAG_EXTINGUISHER	                [Type] = 24
[Name] = EXP_TAG_PROGRAMMABLEAR	                [Type] = 25
[Name] = EXP_TAG_TRAIN	                        [Type] = 26
[Name] = EXP_TAG_BARREL	                        [Type] = 27
[Name] = EXP_TAG_PROPANE	                    [Type] = 28
[Name] = EXP_TAG_BLIMP	                        [Type] = 29
[Name] = EXP_TAG_DIR_FLAME_EXPLODE	            [Type] = 30
[Name] = EXP_TAG_TANKER	                        [Type] = 31
[Name] = EXP_TAG_PLANE_ROCKET	                [Type] = 32
[Name] = EXP_TAG_VEHICLE_BULLET	                [Type] = 33
[Name] = EXP_TAG_GAS_TANK	                    [Type] = 34
[Name] = EXP_TAG_BIRD_CRAP	                    [Type] = 35
[Name] = EXP_TAG_RAILGUN	                    [Type] = 36
[Name] = EXP_TAG_BLIMP2	                        [Type] = 37
[Name] = EXP_TAG_FIREWORK	                    [Type] = 38
[Name] = EXP_TAG_SNOWBALL	                    [Type] = 39
[Name] = EXP_TAG_PROXMINE	                    [Type] = 40
[Name] = EXP_TAG_VALKYRIE_CANNON	            [Type] = 41
[Name] = EXP_TAG_AIR_DEFENSE	                [Type] = 42
[Name] = EXP_TAG_PIPEBOMB	                    [Type] = 43
[Name] = EXP_TAG_VEHICLEMINE	                [Type] = 44
[Name] = EXP_TAG_EXPLOSIVEAMMO	                [Type] = 45
[Name] = EXP_TAG_APCSHELL	                    [Type] = 46
[Name] = EXP_TAG_BOMB_CLUSTER	                [Type] = 47
[Name] = EXP_TAG_BOMB_GAS	                    [Type] = 48
[Name] = EXP_TAG_BOMB_INCENDIARY	            [Type] = 49
[Name] = EXP_TAG_BOMB_STANDARD	                [Type] = 50
[Name] = EXP_TAG_TORPEDO	                    [Type] = 51
[Name] = EXP_TAG_TORPEDO_UNDERWATER	            [Type] = 52
[Name] = EXP_TAG_BOMBUSHKA_CANNON	            [Type] = 53
[Name] = EXP_TAG_BOMB_CLUSTER_SECONDARY	        [Type] = 54
[Name] = EXP_TAG_HUNTER_BARRAGE	                [Type] = 55
[Name] = EXP_TAG_HUNTER_CANNON	                [Type] = 56
[Name] = EXP_TAG_ROGUE_CANNON	                [Type] = 57
[Name] = EXP_TAG_MINE_UNDERWATER	            [Type] = 58
[Name] = EXP_TAG_ORBITAL_CANNON	                [Type] = 59
[Name] = EXP_TAG_BOMB_STANDARD_WIDE	            [Type] = 60
[Name] = EXP_TAG_EXPLOSIVEAMMO_SHOTGUN	        [Type] = 61
[Name] = EXP_TAG_OPPRESSOR2_CANNON	            [Type] = 62
[Name] = EXP_TAG_MORTAR_KINETIC	                [Type] = 63
[Name] = EXP_TAG_VEHICLEMINE_KINETIC	        [Type] = 64
[Name] = EXP_TAG_VEHICLEMINE_EMP	            [Type] = 65
[Name] = EXP_TAG_VEHICLEMINE_SPIKE	            [Type] = 66
[Name] = EXP_TAG_VEHICLEMINE_SLICK	            [Type] = 67
[Name] = EXP_TAG_VEHICLEMINE_TAR	            [Type] = 68
[Name] = EXP_TAG_SCRIPT_DRONE	                [Type] = 69
[Name] = EXP_TAG_RAYGUN	                        [Type] = 70
[Name] = EXP_TAG_BURIEDMINE	                    [Type] = 71
[Name] = EXP_TAG_SCRIPT_MISSILE	                [Type] = 72